# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'FasiaCRM'
- name: LOGO_THUMBNAIL
  value: 'https://fasiacrm.com/wp-content/uploads/2024/01/Vector-1.png'
- name: LOGO
  value: 'https://fasiacrm.com/wp-content/uploads/2024/01/Capa_6.png'
- name: LOGO_DARK
  value: 'https://fasiacrm.com/wp-content/uploads/2024/01/Capa_6.png'
- name: BRAND_URL
  value: 'https://www.fasiacrm.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.fasiacrm.com'
- name: BRAND_NAME
  value: 'FasiaCRM'
- name: TERMS_URL
  value: 'https://www.fasiacrm.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.fasiacrm.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
